version: '3.9'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=myFirstDatabase
  redis:
    image: redis:7.0.5
    ports:
      - 6379:6379
